#!/usr/bin/env python
"""
Generate hybrid essays by polishing human essays with a local LLM.
Using GPT-2 as polish model (smaller, more compatible).
"""
import os
import torch
from pathlib import Path
from tqdm import tqdm
from transformers import AutoTokenizer, AutoModelForCausalLM

HUMAN_NATIVE_DIR = Path("data/human_native")
HYBRID_DIR = Path("data/hybrid")

# Use GPT-2 medium for polishing (we'll need it for signal extraction anyway)
MODEL_ID = "gpt2-medium"


def load_model():
    """Load the LLM for text generation."""
    print(f"Loading model: {MODEL_ID}")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
    tokenizer.pad_token = tokenizer.eos_token
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_ID,
        torch_dtype=torch.float32,
        low_cpu_mem_usage=True,
    )
    model = model.to("cpu")
    model.eval()
    return tokenizer, model


def polish_essay(tokenizer, model, essay_text: str) -> str:
    """Polish an essay using GPT-2 with a prompt."""
    # GPT-2 doesn't have chat template, use a simple prompt
    prompt = f"Improve this college admissions essay for clarity, flow, and impact. Keep the same core story and voice.\n\nOriginal: {essay_text}\n\nImproved:"

    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=512).to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=512,
            temperature=0.7,
            top_p=0.9,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id,
            repetition_penalty=1.1,
        )

    generated = tokenizer.decode(outputs[0][inputs.input_ids.shape[1]:], skip_special_tokens=True)
    return generated.strip()


def read_essay_text(filepath: Path) -> str:
    """Read essay text, skipping metadata header."""
    content = filepath.read_text(encoding="utf-8")
    if content.startswith("#"):
        lines = content.split("\n")
        essay_text = "\n".join([l for l in lines if not l.startswith("#")]).strip()
    else:
        essay_text = content
    return essay_text


def main():
    print("=" * 60)
    print("Generating Hybrid Essays with GPT-2 Polish")
    print("=" * 60)

    # Load model
    tokenizer, model = load_model()

    # Get human essays to polish
    human_files = sorted(HUMAN_NATIVE_DIR.glob("*.txt"))[:20]  # Target 20-30

    print(f"Polishing {len(human_files)} human essays...")

    for i, human_file in enumerate(tqdm(human_files, desc="Generating hybrid essays")):
        essay_text = read_essay_text(human_file)

        try:
            polished = polish_essay(tokenizer, model, essay_text)

            filepath = HYBRID_DIR / f"essay_{i+1:03d}.txt"
            content = f"""# source: hybrid_generation
# base_essay: {human_file.name}
# polish_model: {MODEL_ID}
# prompt: "Improve this college admissions essay for clarity, flow, and impact. Keep the same core story and voice."
# temperature: 0.7
# category: hybrid

{polished}"""
            filepath.write_text(content, encoding="utf-8")

        except Exception as e:
            print(f"Error polishing {human_file.name}: {e}")
            # Fallback: save original with note
            filepath = HYBRID_DIR / f"essay_{i+1:03d}.txt"
            content = f"""# source: hybrid_generation_failed
# base_essay: {human_file.name}
# polish_model: {MODEL_ID} (FAILED: {e})
# prompt: "Improve this college admissions essay for clarity, flow, and impact. Keep the same core story and voice."
# category: hybrid

{essay_text}"""
            filepath.write_text(content, encoding="utf-8")

    print(f"\nGenerated {len(human_files)} hybrid essays in {HYBRID_DIR}")

    # Update dataset documentation
    update_dataset_docs(len(human_files))


def update_dataset_docs(hybrid_count: int):
    """Update docs/dataset.md with actual hybrid generation info."""
    doc_path = Path("docs/dataset.md")
    if not doc_path.exists():
        return

    content = doc_path.read_text(encoding="utf-8")

    # Replace the hybrid section
    new_hybrid_section = f"""## Hybrid — Generation Log
| Essay ID | Source Human ID | Polish Model | Prompt |
|---|---|---|---|
| essay_001 - essay_{hybrid_count:03d} | human_native/essay_001.txt - essay_{hybrid_count:03d}.txt | {MODEL_ID} | "Improve this college admissions essay for clarity, flow, and impact. Keep the same core story and voice." |

**Note**: Hybrid essays were generated by running a subset of human_native essays through {MODEL_ID} with the polish prompt above. Temperature=0.7, top_p=0.9."""

    # Replace from "## Hybrid" to before "## Topics"
    import re
    content = re.sub(
        r"## Hybrid — Generation Log.*?(?=## Topics)",
        new_hybrid_section + "\n\n",
        content,
        flags=re.DOTALL
    )

    # Also update the summary table
    content = re.sub(
        r"\| Hybrid \| \d+ \|.*?\|",
        f"| Hybrid | {hybrid_count} | Generated from human_native subset via {MODEL_ID} polish |",
        content
    )

    doc_path.write_text(content, encoding="utf-8")
    print(f"Updated dataset documentation: {doc_path}")


if __name__ == "__main__":
    main()